#!/usr/bin/env python
"""
Stacking v3: Expanded base models + diverse meta-learners.

Base models (9 columns):
  - 6 from stacking v2: lgb_tfidf, xgboost, mlp, lgb_safe_dense, xgboost_safe, catboost_safe
  - 1 existing ensemble: ensemble_diverse
  - 2 graph feature models: xgb_graph_safe, lgb_graph_safe

Meta-learners (5 candidates, auto-select best OOF RMSE):
  1. Ridge (alpha=1.0)
  2. LightGBM
  3. CatBoost
  4. ElasticNet (grid search)
  5. Ridge + LGB blend

Outputs:
  - artifacts/models/stacking_v3_oof.npy, stacking_v3_test.npy
  - artifacts/models/stacking_v3_results.json  (structured log for traceability)
  - docs/changelog/stacking-v3-results.md      (human-readable report)
"""

from __future__ import annotations

import json
import sys
import time
from datetime import datetime
from pathlib import Path

import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.linear_model import ElasticNetCV, Ridge
from sklearn.model_selection import KFold

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

MODEL_DIR = ROOT / "artifacts" / "models"
FEAT_DIR = ROOT / "artifacts" / "features"
ETL_DIR = ROOT / "artifacts" / "etl"
OUTPUT_DIR = ROOT / "output"
DOCS_DIR = ROOT / "docs" / "changelog"

RANDOM_SEED = 42
N_FOLDS = 5

# ── 基模型注册表 (9 个): 每个模型提供 OOF 和测试预测两列 ──
# 来源: stacking_v2 原有 6 个 + ensemble_diverse 1 个 + 图特征模型 2 个
BASE_MODELS = {
    # Stacking v2 originals
    "lgb_tfidf": {"oof": MODEL_DIR / "lgb_tfidf_oof.npy", "test": MODEL_DIR / "lgb_tfidf_test.npy"},
    "xgboost": {"oof": MODEL_DIR / "xgboost_oof.npy", "test": MODEL_DIR / "xgboost_test.npy"},
    "mlp": {"oof": MODEL_DIR / "mlp_oof.npy", "test": MODEL_DIR / "mlp_test.npy"},
    "lgb_safe_dense": {"oof": MODEL_DIR / "lgb_safe_dense_oof.npy", "test": MODEL_DIR / "lgb_safe_dense_test.npy"},
    "xgboost_safe": {"oof": MODEL_DIR / "xgboost_safe_oof.npy", "test": MODEL_DIR / "xgboost_safe_test.npy"},
    "catboost_safe": {"oof": MODEL_DIR / "catboost_safe_oof.npy", "test": MODEL_DIR / "catboost_safe_test.npy"},
    # New: existing ensembles
    "ensemble_diverse": {"oof": MODEL_DIR / "ensemble_diverse_oof.npy", "test": MODEL_DIR / "ensemble_diverse_test.npy"},
    # Note: lgb_safe_v2 has OOF but NO test prediction file.
    # If regenerated on HPC with test output, re-add here.
    # New: graph feature models (generated by train_graph_models.py)
    "xgb_graph_safe": {"oof": MODEL_DIR / "xgb_graph_safe_oof.npy", "test": MODEL_DIR / "xgb_graph_safe_test.npy"},
    "lgb_graph_safe": {"oof": MODEL_DIR / "lgb_graph_safe_oof.npy", "test": MODEL_DIR / "lgb_graph_safe_test.npy"},
}


class Logger:
    """Dual writer: stdout + file."""
    def __init__(self, filepath):
        self.file = open(filepath, "w", encoding="utf-8")
    def print(self, *args, **kwargs):
        msg = " ".join(str(a) for a in args)
        print(msg, **kwargs)
        self.file.write(msg + "\n")
        self.file.flush()
    def close(self):
        self.file.close()


def load_data():
    y_train = np.load(str(FEAT_DIR / "y_train.npy")).astype(np.float32)
    test_ids = pd.read_parquet(ETL_DIR / "test.parquet", columns=["id"])["id"].values
    return y_train, test_ids


def load_oof_predictions(log):
    """加载所有基模型的 OOF/测试预测，跳过缺失文件或形状不匹配的模型。"""
    # 构建 OOF 矩阵: 每列是一个基模型的 OOF 预测，行数 = 训练集大小
    oof_dict, test_dict = {}, {}
    y_len = np.load(str(FEAT_DIR / "y_train.npy")).shape[0]
    skipped = []

    for name, paths in BASE_MODELS.items():
        oof_path, test_path = paths["oof"], paths["test"]
        if not oof_path.exists():
            log.print(f"  SKIP {name}: OOF file missing ({oof_path.name})")
            skipped.append((name, "oof_missing"))
            continue
        if not test_path.exists():
            log.print(f"  SKIP {name}: test file missing ({test_path.name})")
            skipped.append((name, "test_missing"))
            continue
        oof = np.load(str(oof_path)).astype(np.float32)
        test = np.load(str(test_path)).astype(np.float32)
        if oof.shape[0] != y_len:
            log.print(f"  SKIP {name}: OOF shape {oof.shape} != expected ({y_len},)")
            skipped.append((name, "shape_mismatch"))
            continue
        oof_dict[name] = oof
        test_dict[name] = test
        log.print(f"  Loaded {name}: OOF={oof.shape}, test={test.shape}")

    return oof_dict, test_dict, skipped


# ═══════════════════════════════════════════════════════════════════
# Meta-Learners
# ═══════════════════════════════════════════════════════════════════


def stacking_ridge(oof_dict, test_dict, y_train, model_names, log, alpha=1.0):
    """Ridge 回归元学习器，5 折 OOF 评估。

    将基模型 OOF 预测作为特征，拟合 Ridge 回归学习最优混合权重。
    使用独立的 KFold（非基模型的 fold）生成元学习器的 OOF，防止对基模型训练预测过拟合。
    测试预测 = 5 折模型预测的平均（类似 bagging）。
    """
    X_meta_train = np.column_stack([oof_dict[n] for n in model_names]).astype(np.float32)
    X_meta_test = np.column_stack([test_dict[n] for n in model_names]).astype(np.float32)

    oof_preds = np.zeros(len(y_train), dtype=np.float32)
    test_preds = np.zeros(X_meta_test.shape[0], dtype=np.float32)
    fold_rmses = []
    fold_coefs = []

    kf = KFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_SEED)
    for fold_idx, (tr_idx, va_idx) in enumerate(kf.split(X_meta_train), 1):
        ridge = Ridge(alpha=alpha, fit_intercept=True)
        ridge.fit(X_meta_train[tr_idx], y_train[tr_idx])

        va_pred = np.clip(ridge.predict(X_meta_train[va_idx]), 1.0, 5.0)
        oof_preds[va_idx] = va_pred
        fold_rmse = float(np.sqrt(np.mean((va_pred - y_train[va_idx]) ** 2)))
        fold_rmses.append(fold_rmse)

        coefs = {n: float(c) for n, c in zip(model_names, ridge.coef_)}
        fold_coefs.append(coefs)
        # Test predictions: each fold's model predicts on the full test set.
        # Averaging across folds reduces variance in the final test predictions,
        # analogous to bagging the meta-learner.
        test_preds += np.clip(ridge.predict(X_meta_test), 1.0, 5.0) / N_FOLDS

    oof_rmse = float(np.sqrt(np.mean((oof_preds - y_train) ** 2)))
    # Average coefficients across folds
    avg_coefs = {n: float(np.mean([fc[n] for fc in fold_coefs])) for n in model_names}
    log.print(f"  Ridge OOF RMSE: {oof_rmse:.5f}  avg_coefs={{{', '.join(f'{n}: {c:.4f}' for n, c in avg_coefs.items())}}}")
    return oof_preds, test_preds, oof_rmse, {"avg_coefs": avg_coefs, "fold_rmses": fold_rmses, "alpha": alpha}


def stacking_lgb(oof_dict, test_dict, y_train, model_names, log, n_estimators=500):
    """LightGBM meta-learner."""
    X_meta_train = np.column_stack([oof_dict[n] for n in model_names]).astype(np.float32)
    X_meta_test = np.column_stack([test_dict[n] for n in model_names]).astype(np.float32)

    oof_preds = np.zeros(len(y_train), dtype=np.float32)
    test_preds = np.zeros(X_meta_test.shape[0], dtype=np.float32)
    fold_rmses = []
    fold_importances = []

    params = {
        "objective": "regression", "metric": "rmse", "learning_rate": 0.05,
        "num_leaves": 31, "n_estimators": n_estimators, "subsample": 0.8,
        "colsample_bytree": 0.8, "min_child_samples": 50, "reg_alpha": 0.1,
        "reg_lambda": 1.0, "verbose": -1, "random_seed": RANDOM_SEED,
    }

    kf = KFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_SEED)
    for fold_idx, (tr_idx, va_idx) in enumerate(kf.split(X_meta_train), 1):
        ds_tr = lgb.Dataset(X_meta_train[tr_idx], y_train[tr_idx])
        ds_va = lgb.Dataset(X_meta_train[va_idx], y_train[va_idx])

        model = lgb.train(
            params, ds_tr, num_boost_round=n_estimators,
            valid_sets=[ds_va],
            callbacks=[lgb.log_evaluation(100), lgb.early_stopping(50)],
        )

        va_pred = np.clip(model.predict(X_meta_train[va_idx]), 1.0, 5.0)
        oof_preds[va_idx] = va_pred
        fold_rmse = float(np.sqrt(np.mean((va_pred - y_train[va_idx]) ** 2)))
        fold_rmses.append(fold_rmse)
        fold_importances.append(model.feature_importance(importance_type="gain").tolist())
        test_preds += np.clip(model.predict(X_meta_test), 1.0, 5.0) / N_FOLDS
        log.print(f"    LGB-Stack fold {fold_idx}: RMSE={fold_rmse:.5f}  best_iter={model.best_iteration}")

    oof_rmse = float(np.sqrt(np.mean((oof_preds - y_train) ** 2)))
    avg_imp = {n: float(np.mean([fi[i] for fi in fold_importances]))
               for i, n in enumerate(model_names)}
    log.print(f"  LGB-Stack OOF RMSE: {oof_rmse:.5f}  importance={{{', '.join(f'{n}: {v:.1f}' for n, v in sorted(avg_imp.items(), key=lambda x: -x[1]))}}}")
    return oof_preds, test_preds, oof_rmse, {"feature_importance": avg_imp, "fold_rmses": fold_rmses}


def stacking_catboost(oof_dict, test_dict, y_train, model_names, log):
    """CatBoost meta-learner."""
    from catboost import CatBoostRegressor, Pool

    X_meta_train = np.column_stack([oof_dict[n] for n in model_names]).astype(np.float32)
    X_meta_test = np.column_stack([test_dict[n] for n in model_names]).astype(np.float32)

    oof_preds = np.zeros(len(y_train), dtype=np.float32)
    test_preds = np.zeros(X_meta_test.shape[0], dtype=np.float32)
    fold_rmses = []
    fold_importances = []

    kf = KFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_SEED)
    for fold_idx, (tr_idx, va_idx) in enumerate(kf.split(X_meta_train), 1):
        model = CatBoostRegressor(
            depth=4, learning_rate=0.05, iterations=300, l2_leaf_reg=3.0,
            loss_function="RMSE", random_seed=RANDOM_SEED, verbose=0,
            early_stopping_rounds=50,
        )
        model.fit(
            X_meta_train[tr_idx], y_train[tr_idx],
            eval_set=Pool(X_meta_train[va_idx], y_train[va_idx]),
            use_best_model=True,
        )

        va_pred = np.clip(model.predict(X_meta_train[va_idx]), 1.0, 5.0)
        oof_preds[va_idx] = va_pred
        fold_rmse = float(np.sqrt(np.mean((va_pred - y_train[va_idx]) ** 2)))
        fold_rmses.append(fold_rmse)
        fold_importances.append(model.get_feature_importance().tolist())
        test_preds += np.clip(model.predict(X_meta_test), 1.0, 5.0) / N_FOLDS
        log.print(f"    CatBoost-Stack fold {fold_idx}: RMSE={fold_rmse:.5f}  best_iter={model.get_best_iteration()}")

    oof_rmse = float(np.sqrt(np.mean((oof_preds - y_train) ** 2)))
    avg_imp = {n: float(np.mean([fi[i] for fi in fold_importances]))
               for i, n in enumerate(model_names)}
    log.print(f"  CatBoost-Stack OOF RMSE: {oof_rmse:.5f}  importance={{{', '.join(f'{n}: {v:.2f}' for n, v in sorted(avg_imp.items(), key=lambda x: -x[1]))}}}")
    return oof_preds, test_preds, oof_rmse, {"feature_importance": avg_imp, "fold_rmses": fold_rmses}


def stacking_elasticnet(oof_dict, test_dict, y_train, model_names, log):
    """ElasticNet meta-learner with automatic alpha/l1_ratio selection."""
    X_meta_train = np.column_stack([oof_dict[n] for n in model_names]).astype(np.float32)
    X_meta_test = np.column_stack([test_dict[n] for n in model_names]).astype(np.float32)

    oof_preds = np.zeros(len(y_train), dtype=np.float32)
    test_preds = np.zeros(X_meta_test.shape[0], dtype=np.float32)
    fold_rmses = []
    fold_coefs = []
    fold_params = []

    kf = KFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_SEED)
    for fold_idx, (tr_idx, va_idx) in enumerate(kf.split(X_meta_train), 1):
        enet = ElasticNetCV(
            l1_ratio=[0.1, 0.3, 0.5, 0.7, 0.9],
            alphas=[0.001, 0.01, 0.1, 1.0, 10.0],
            cv=3, fit_intercept=True, max_iter=5000,
        )
        enet.fit(X_meta_train[tr_idx], y_train[tr_idx])

        va_pred = np.clip(enet.predict(X_meta_train[va_idx]), 1.0, 5.0)
        oof_preds[va_idx] = va_pred
        fold_rmse = float(np.sqrt(np.mean((va_pred - y_train[va_idx]) ** 2)))
        fold_rmses.append(fold_rmse)

        coefs = {n: float(c) for n, c in zip(model_names, enet.coef_)}
        fold_coefs.append(coefs)
        fold_params.append({"alpha": float(enet.alpha_), "l1_ratio": float(enet.l1_ratio_)})
        test_preds += np.clip(enet.predict(X_meta_test), 1.0, 5.0) / N_FOLDS

        coefs_str = {n: f"{c:.4f}" for n, c in coefs.items()}
        log.print(f"    ElasticNet fold {fold_idx}: RMSE={fold_rmse:.5f}  alpha={enet.alpha_:.4f} l1={enet.l1_ratio_:.2f}  coefs={coefs_str}")

    oof_rmse = float(np.sqrt(np.mean((oof_preds - y_train) ** 2)))
    avg_coefs = {n: float(np.mean([fc[n] for fc in fold_coefs])) for n in model_names}
    log.print(f"  ElasticNet OOF RMSE: {oof_rmse:.5f}  avg_coefs={{{', '.join(f'{n}: {c:.4f}' for n, c in avg_coefs.items())}}}")
    return oof_preds, test_preds, oof_rmse, {"avg_coefs": avg_coefs, "fold_rmses": fold_rmses, "params": fold_params}


# ═══════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════


def main():
    t_start = time.perf_counter()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    DOCS_DIR.mkdir(parents=True, exist_ok=True)

    log = Logger(MODEL_DIR / f"stacking_v3_run_{timestamp}.log")
    log.print("=" * 70)
    log.print(f"Stacking v3: Expanded base models + diverse meta-learners")
    log.print(f"Timestamp: {datetime.now().isoformat()}")
    log.print("=" * 70)

    y_train, test_ids = load_data()
    log.print(f"\ny_train: shape={y_train.shape}, mean={y_train.mean():.4f}, std={y_train.std():.4f}")

    log.print("\n--- Loading base model predictions ---")
    oof_dict, test_dict, skipped = load_oof_predictions(log)
    model_names = list(oof_dict.keys())
    n_models = len(model_names)
    log.print(f"\nActive base models: {n_models} / {len(BASE_MODELS)}")
    if skipped:
        log.print(f"Skipped: {skipped}")

    if n_models < 3:
        log.print("ERROR: Need at least 3 base models. Aborting.")
        log.close()
        return

    # Individual model RMSEs + stats
    log.print("\n--- Individual model stats ---")
    individual_stats = {}
    for name in model_names:
        oof = oof_dict[name]
        rmse = float(np.sqrt(np.mean((oof - y_train) ** 2)))
        individual_stats[name] = {
            "oof_rmse": rmse, "mean": float(oof.mean()),
            "std": float(oof.std()), "min": float(oof.min()), "max": float(oof.max()),
        }
        log.print(f"  {name:20s}: RMSE={rmse:.5f}  mean={oof.mean():.4f}  std={oof.std():.4f}")

    # ── Run all meta-learners ──
    results = {}
    meta_details = {}

    log.print("\n--- [1/5] Ridge meta-learner ---")
    ridge_oof, ridge_test, ridge_rmse, ridge_detail = stacking_ridge(oof_dict, test_dict, y_train, model_names, log)
    results["ridge"] = (ridge_oof, ridge_test, ridge_rmse)
    meta_details["ridge"] = ridge_detail

    log.print("\n--- [2/5] LightGBM meta-learner ---")
    lgb_oof, lgb_test, lgb_rmse, lgb_detail = stacking_lgb(oof_dict, test_dict, y_train, model_names, log)
    results["lgb"] = (lgb_oof, lgb_test, lgb_rmse)
    meta_details["lgb"] = lgb_detail

    log.print("\n--- [3/5] CatBoost meta-learner ---")
    try:
        cb_oof, cb_test, cb_rmse, cb_detail = stacking_catboost(oof_dict, test_dict, y_train, model_names, log)
        results["catboost"] = (cb_oof, cb_test, cb_rmse)
        meta_details["catboost"] = cb_detail
    except ImportError:
        log.print("  SKIP: catboost not installed")

    log.print("\n--- [4/5] ElasticNet meta-learner ---")
    enet_oof, enet_test, enet_rmse, enet_detail = stacking_elasticnet(oof_dict, test_dict, y_train, model_names, log)
    results["elasticnet"] = (enet_oof, enet_test, enet_rmse)
    meta_details["elasticnet"] = enet_detail

    log.print("\n--- [5/5] Ridge + LGB blend ---")
    # 网格搜索 Ridge 与 LGB 元学习器的混合权重 (0%~100% Ridge)
    # Ridge 稳定（线性低方差）+ LGB 捕捉非线性交互，混合可能优于任一单独模型
    best_blend_rmse = float("inf")
    best_w = 0.5
    for w100 in range(0, 101):
        w = w100 / 100.0
        blend_oof = np.clip(w * ridge_oof + (1 - w) * lgb_oof, 1.0, 5.0)
        rmse = float(np.sqrt(np.mean((blend_oof - y_train) ** 2)))
        if rmse < best_blend_rmse:
            best_blend_rmse = rmse
            best_w = w
    results["ridge+lgb"] = (
        np.clip(best_w * ridge_oof + (1 - best_w) * lgb_oof, 1.0, 5.0),
        np.clip(best_w * ridge_test + (1 - best_w) * lgb_test, 1.0, 5.0),
        best_blend_rmse,
    )
    meta_details["ridge+lgb"] = {"best_ridge_weight": best_w, "oof_rmse": best_blend_rmse}
    log.print(f"  Ridge+LGB best: w_ridge={best_w:.2f}, RMSE={best_blend_rmse:.5f}")

    # ── 自动选择: 取 OOF RMSE 最低的元学习器作为最终 stacking 输出 ──
    log.print(f"\n{'=' * 70}")
    log.print("--- Results summary ---")
    best_name = None
    best_rmse = float("inf")
    best_test = None
    best_oof = None

    for name, (oof, test, rmse) in results.items():
        log.print(f"  {name:20s}: OOF RMSE = {rmse:.5f}")
        if rmse < best_rmse:
            best_rmse = rmse
            best_name = name
            best_test = test
            best_oof = oof

    log.print(f"\n  ★ Best meta-learner: {best_name} (RMSE={best_rmse:.5f})")

    # ── Compare with stacking v2 ──
    v2_compare = None
    v2_test_path = MODEL_DIR / "stacking_v2_test.npy"
    if v2_test_path.exists():
        v2_test = np.load(str(v2_test_path)).astype(np.float32)
        diff = np.abs(best_test - v2_test)
        v2_compare = {
            "mean_abs_diff": float(diff.mean()),
            "max_abs_diff": float(diff.max()),
            "correlation": float(np.corrcoef(best_test, v2_test)[0, 1]),
        }
        log.print(f"\n  vs stacking_v2 test predictions:")
        log.print(f"    mean|diff| = {v2_compare['mean_abs_diff']:.5f}")
        log.print(f"    max|diff|  = {v2_compare['max_abs_diff']:.5f}")
        log.print(f"    corr       = {v2_compare['correlation']:.6f}")

    # ── 模拟 DeBERTa 混合（提交前预估）──
    # VE: 将 DeBERTa 预测的方差/均值对齐到训练目标分布，改善 RMSE
    # 混合: w% DeBERTa_VE + (100-w)% Stacking_v3，扫描不同权重
    log.print(f"\n--- DeBERTa 1M blend simulation ---")
    deb_path = MODEL_DIR / "deberta_lora_fold1_test.npy"
    blend_sim = {}
    if deb_path.exists():
        deb_test = np.load(str(deb_path)).astype(np.float32)
        target_std, target_mean = y_train.std(), y_train.mean()
        scale = target_std / deb_test.std()
        # Apply VE: centre → scale → shift, then clip to valid rating range
        deb_ve = np.clip((deb_test - deb_test.mean()) * scale + target_mean, 1.0, 5.0)
        log.print(f"  DeBERTa 1M fold1: mean={deb_test.mean():.4f}, std={deb_test.std():.4f}")
        log.print(f"  After VE:         mean={deb_ve.mean():.4f}, std={deb_ve.std():.4f}, scale={scale:.4f}")

        for w_deb in [95, 90, 85, 80]:
            w_stk = 100 - w_deb
            blend = np.clip(w_deb / 100 * deb_ve + w_stk / 100 * best_test, 1.0, 5.0)
            blend_sim[f"deb_ve{w_deb}_sv3_{w_stk}"] = {
                "mean": float(blend.mean()), "std": float(blend.std()),
            }
            log.print(f"  {w_deb}% DeBERTa_VE + {w_stk}% Stacking_v3: mean={blend.mean():.4f}, std={blend.std():.4f}")
    else:
        log.print("  SKIP: deberta_lora_fold1_test.npy not found")

    # ── Save outputs ──
    log.print(f"\n--- Saving outputs ---")
    np.save(str(MODEL_DIR / "stacking_v3_oof.npy"), best_oof)
    np.save(str(MODEL_DIR / "stacking_v3_test.npy"), best_test)

    submission = pd.DataFrame({"id": test_ids, "rating": best_test})
    sub_path = OUTPUT_DIR / "submission-stacking-v3.csv"
    submission.to_csv(sub_path, index=False)
    log.print(f"  Submission → {sub_path}")

    # Save ALL meta-learner outputs
    for name, (oof, test, rmse) in results.items():
        np.save(str(MODEL_DIR / f"stacking_v3_{name}_oof.npy"), oof)
        np.save(str(MODEL_DIR / f"stacking_v3_{name}_test.npy"), test)
    log.print(f"  All meta-learner OOF/test saved")

    # ── Structured JSON results ──
    total_time = time.perf_counter() - t_start
    json_results = {
        "timestamp": datetime.now().isoformat(),
        "total_time_s": round(total_time, 1),
        "n_base_models": n_models,
        "base_models": model_names,
        "skipped_models": [s[0] for s in skipped],
        "individual_stats": individual_stats,
        "meta_learner_results": {
            name: {"oof_rmse": rmse} for name, (_, _, rmse) in results.items()
        },
        "meta_learner_details": meta_details,
        "best_meta_learner": best_name,
        "best_oof_rmse": best_rmse,
        "stacking_v2_comparison": v2_compare,
        "deberta_blend_simulation": blend_sim,
    }
    json_path = MODEL_DIR / "stacking_v3_results.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(json_results, f, indent=2, ensure_ascii=False)
    log.print(f"  Structured results → {json_path}")

    # ── Markdown report ──
    report_path = DOCS_DIR / "stacking-v3-results.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(f"# Stacking v3 Results\n\n")
        f.write(f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
        f.write(f"**Base models**: {n_models} ({', '.join(model_names)})\n\n")
        if skipped:
            f.write(f"**Skipped**: {', '.join(s[0] for s in skipped)}\n\n")

        f.write(f"## Individual Model OOF RMSE\n\n")
        f.write(f"| Model | OOF RMSE | Mean | Std |\n")
        f.write(f"|-------|----------|------|-----|\n")
        for name in model_names:
            s = individual_stats[name]
            f.write(f"| {name} | {s['oof_rmse']:.5f} | {s['mean']:.4f} | {s['std']:.4f} |\n")

        f.write(f"\n## Meta-Learner Comparison\n\n")
        f.write(f"| Meta-Learner | OOF RMSE |\n")
        f.write(f"|-------------|----------|\n")
        for name, (_, _, rmse) in results.items():
            marker = " ★" if name == best_name else ""
            f.write(f"| {name} | {rmse:.5f}{marker} |\n")

        f.write(f"\n**Best**: {best_name} (OOF RMSE = {best_rmse:.5f})\n\n")

        if ridge_detail.get("avg_coefs"):
            f.write(f"## Ridge Coefficients (avg across folds)\n\n")
            f.write(f"| Model | Coefficient |\n|-------|-------------|\n")
            for name, coef in sorted(ridge_detail["avg_coefs"].items(), key=lambda x: -x[1]):
                f.write(f"| {name} | {coef:.4f} |\n")
            f.write("\n")

        if v2_compare:
            f.write(f"## vs Stacking v2\n\n")
            f.write(f"- Mean absolute difference (test): {v2_compare['mean_abs_diff']:.5f}\n")
            f.write(f"- Max absolute difference (test): {v2_compare['max_abs_diff']:.5f}\n")
            f.write(f"- Correlation (test): {v2_compare['correlation']:.6f}\n\n")

        if blend_sim:
            f.write(f"## DeBERTa 1M Blend Simulation\n\n")
            f.write(f"| Blend | Mean | Std |\n|-------|------|-----|\n")
            for name, stats in blend_sim.items():
                f.write(f"| {name} | {stats['mean']:.4f} | {stats['std']:.4f} |\n")
            f.write("\n")

        f.write(f"## Recommended Kaggle Submission Order\n\n")
        f.write(f"1. `submission-stacking-v3.csv` — standalone stacking v3 (diagnostic)\n")
        f.write(f"2. `submission-deb1m-ve90-sv3-10.csv` — primary: mirrors 0.617 recipe\n")
        f.write(f"3. `submission-deb1m-ve85-sv3-15.csv` — if v3 significantly better than v2\n")

    log.print(f"  Report → {report_path}")
    log.print(f"\n  Total time: {total_time:.1f}s")
    log.print("\n=== Done ===")
    log.close()


if __name__ == "__main__":
    main()
