#!/usr/bin/env python3
"""
Generate 2 competitive submissions for DeBERTa-v3-large:
1. Large model VE only (ablation: Large vs Base)
2. Large model VE 60% + Stacking V3 ridge+lgb 40% (same recipe as current best 0.59770)

Target: Beat current best 0.59770 (Base model VE60 + Stacking V3 rlg40)
"""

import numpy as np
import pandas as pd
from pathlib import Path

print("=" * 60)
print("Generating Large Model Submissions")
print("=" * 60)

# ============================================================
# 1. Load predictions
# ============================================================

print("\n[1/4] Loading predictions...")

# Large model averaged test predictions (generated by training script)
large_test = np.load("artifacts/models/deberta_large_full_test.npy")
print(f"  Large model: {large_test.shape}, mean={large_test.mean():.4f}, std={large_test.std():.4f}")

# Stacking V3 ridge+lgb (same as current best submission)
stacking_rlg = np.load("artifacts/models/stacking_v3_ridge+lgb_test.npy")
print(f"  Stacking V3 rlg: {stacking_rlg.shape}, mean={stacking_rlg.mean():.4f}, std={stacking_rlg.std():.4f}")

# Training labels for VE parameters
y_train = np.load("artifacts/features/y_train.npy").astype(np.float32)
target_mean = y_train.mean()
target_std = y_train.std()
print(f"  Target: mean={target_mean:.4f}, std={target_std:.4f}")

# Test IDs
test_ids = np.load("artifacts/models/test_tokens.npz", allow_pickle=True)["ids"]
print(f"  Test samples: {len(test_ids)}")

# ============================================================
# 2. Apply Variance Expansion (VE)
# ============================================================

print("\n[2/4] Applying Variance Expansion...")

pred_mean = large_test.mean()
pred_std = large_test.std()
scale = target_std / pred_std

ve_large = np.clip((large_test - pred_mean) * scale + target_mean, 1.0, 5.0)
print(f"  VE Large: mean={ve_large.mean():.4f}, std={ve_large.std():.4f}")

# ============================================================
# 3. Generate submissions
# ============================================================

print("\n[3/4] Generating submissions...")

# Submission 1: Large model VE only (ablation)
sub1 = ve_large
pd.DataFrame({"id": range(len(sub1)), "rating": sub1}).to_csv(
    "output/sub-large-ve-only.csv", index=False
)
print(f"  ✓ sub-large-ve-only.csv (Large VE only)")
print(f"    mean={sub1.mean():.4f}, std={sub1.std():.4f}")

# Submission 2: Large model VE 60% + Stacking V3 rlg 40% (same as current best)
sub2 = np.clip(0.60 * ve_large + 0.40 * stacking_rlg, 1.0, 5.0)
pd.DataFrame({"id": range(len(sub2)), "rating": sub2}).to_csv(
    "output/sub-large-ve60-rlg40.csv", index=False
)
print(f"  ✓ sub-large-ve60-rlg40.csv (Large VE 60% + Stacking V3 rlg 40%)")
print(f"    mean={sub2.mean():.4f}, std={sub2.std():.4f}")

# ============================================================
# 4. Summary
# ============================================================

print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)

print("\n📊 Submissions generated:")
print("  1. sub-large-ve-only.csv")
print(f"     Purpose: Ablation - Large model VE vs Base model VE")
print(f"     Compare with: sub-deb1m-ve-only.csv (if exists)")
print()
print("  2. sub-large-ve60-rlg40.csv")
print(f"     Purpose: Beat current best 0.59770")
print(f"     Same recipe as: sub-deb1m-ve60-sv3rlg40.csv (Kaggle 0.59770)")
print(f"     Only difference: Large model replaces Base model")

print("\n💡 Submission priority:")
print("  1. sub-large-ve60-rlg40.csv (most likely to beat 0.59770)")
print("  2. sub-large-ve-only.csv (ablation to understand Large model)")

print("\n" + "=" * 60)
